title: Yu Liu # your name (or website title) here
logo: "/images/1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Interdisciplinary background of Data Science and Life Science. Looking for full time Data Scientist position. 
  <br><br>
  # # *Skills*
  <br>
  Progamming: Python, R, SQL, D3.js
  <br>
  Machine Learning: Regression, Clustering, Classification, Tree-based models, Time Series
  <br>
  Big Data: Hadoop, GCP, AWS, Spark, Hive, Pig
  <br>
  Visualization: ggplot2(R), matplotlib(Python), Tableau, D3.js
  <br><br>
  <a href="https://www.linkedin.com/in/yu-liu-8985b59b">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
